/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedAccountRouteImport } from './routes/_protected/account'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authAuthRouteRouteImport } from './routes/(auth)/_auth/route'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as authAuthSignupIndexRouteImport } from './routes/(auth)/_auth/signup/index'
import { Route as authAuthSigninIndexRouteImport } from './routes/(auth)/_auth/signin/index'
import { Route as authAuthCheckEmailIndexRouteImport } from './routes/(auth)/_auth/check-email/index'
import { Route as authAuthSigninVerifyEmailTokenRouteImport } from './routes/(auth)/_auth/signin/verify-email/$token'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRouteRoute = authAuthRouteRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const authAuthSignupIndexRoute = authAuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => authAuthRouteRoute,
} as any)
const authAuthSigninIndexRoute = authAuthSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => authAuthRouteRoute,
} as any)
const authAuthCheckEmailIndexRoute = authAuthCheckEmailIndexRouteImport.update({
  id: '/check-email/',
  path: '/check-email/',
  getParentRoute: () => authAuthRouteRoute,
} as any)
const authAuthSigninVerifyEmailTokenRoute =
  authAuthSigninVerifyEmailTokenRouteImport.update({
    id: '/signin/verify-email/$token',
    path: '/signin/verify-email/$token',
    getParentRoute: () => authAuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/account': typeof ProtectedAccountRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/check-email/': typeof authAuthCheckEmailIndexRoute
  '/signin/': typeof authAuthSigninIndexRoute
  '/signup/': typeof authAuthSignupIndexRoute
  '/signin/verify-email/$token': typeof authAuthSigninVerifyEmailTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/account': typeof ProtectedAccountRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/check-email': typeof authAuthCheckEmailIndexRoute
  '/signin': typeof authAuthSigninIndexRoute
  '/signup': typeof authAuthSignupIndexRoute
  '/signin/verify-email/$token': typeof authAuthSigninVerifyEmailTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/(auth)/_auth': typeof authAuthRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/_protected/account': typeof ProtectedAccountRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/(auth)/_auth/check-email/': typeof authAuthCheckEmailIndexRoute
  '/(auth)/_auth/signin/': typeof authAuthSigninIndexRoute
  '/(auth)/_auth/signup/': typeof authAuthSignupIndexRoute
  '/(auth)/_auth/signin/verify-email/$token': typeof authAuthSigninVerifyEmailTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/account'
    | '/dashboard/'
    | '/check-email/'
    | '/signin/'
    | '/signup/'
    | '/signin/verify-email/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/account'
    | '/dashboard'
    | '/check-email'
    | '/signin'
    | '/signup'
    | '/signin/verify-email/$token'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/about'
    | '/(auth)/_auth'
    | '/(auth)/forgot-password'
    | '/_protected/account'
    | '/_protected/dashboard/'
    | '/(auth)/_auth/check-email/'
    | '/(auth)/_auth/signin/'
    | '/(auth)/_auth/signup/'
    | '/(auth)/_auth/signin/verify-email/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  authAuthRouteRoute: typeof authAuthRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/(auth)/_auth/signup/': {
      id: '/(auth)/_auth/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof authAuthSignupIndexRouteImport
      parentRoute: typeof authAuthRouteRoute
    }
    '/(auth)/_auth/signin/': {
      id: '/(auth)/_auth/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof authAuthSigninIndexRouteImport
      parentRoute: typeof authAuthRouteRoute
    }
    '/(auth)/_auth/check-email/': {
      id: '/(auth)/_auth/check-email/'
      path: '/check-email'
      fullPath: '/check-email/'
      preLoaderRoute: typeof authAuthCheckEmailIndexRouteImport
      parentRoute: typeof authAuthRouteRoute
    }
    '/(auth)/_auth/signin/verify-email/$token': {
      id: '/(auth)/_auth/signin/verify-email/$token'
      path: '/signin/verify-email/$token'
      fullPath: '/signin/verify-email/$token'
      preLoaderRoute: typeof authAuthSigninVerifyEmailTokenRouteImport
      parentRoute: typeof authAuthRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedAccountRoute: typeof ProtectedAccountRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAccountRoute: ProtectedAccountRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface authAuthRouteRouteChildren {
  authAuthCheckEmailIndexRoute: typeof authAuthCheckEmailIndexRoute
  authAuthSigninIndexRoute: typeof authAuthSigninIndexRoute
  authAuthSignupIndexRoute: typeof authAuthSignupIndexRoute
  authAuthSigninVerifyEmailTokenRoute: typeof authAuthSigninVerifyEmailTokenRoute
}

const authAuthRouteRouteChildren: authAuthRouteRouteChildren = {
  authAuthCheckEmailIndexRoute: authAuthCheckEmailIndexRoute,
  authAuthSigninIndexRoute: authAuthSigninIndexRoute,
  authAuthSignupIndexRoute: authAuthSignupIndexRoute,
  authAuthSigninVerifyEmailTokenRoute: authAuthSigninVerifyEmailTokenRoute,
}

const authAuthRouteRouteWithChildren = authAuthRouteRoute._addFileChildren(
  authAuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  authAuthRouteRoute: authAuthRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
